Error: Invalid src prop (https://drive.google.com/file/d/1aU9Y2J8RWaXT2kgjdGVrWgIfUaIjrLqq/view?usp=sharing) on `next/image`, hostname "drive.google.com" is not configured under images in your `next.config.js` See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
src/components/admin/item-manager.tsx (189:21) @ ItemManager

  187 |             {formData.imageUrl && (
  188 |                 <div className="my-2">
> 189 |                     <Image src={formData.imageUrl} alt="Preview" width={80} height={80} className="rounded object-cover border" data-ai-hint="image preview" onError={(e) => (e.currentTarget.src = 'https://placehold.co/80x80.png?text=Invalid')} />
      |                     ^
  190 |                 </div>
  191 |             )}
  192 |             <div>
Call Stack
9

Show 6 ignore-listed frame(s)
Array.map
<anonymous> (0:0)
ItemManager
src/components/admin/item-manager.tsx (189:21)
AdminPage
src/app/admin/page.tsx (110:11)
no the issue is i will upload some images for the furniture item from the google link or my google drive so the image can be form any where but 99% of the time i will uplaod image form the google drive link so make sure to fisx this